name: iPhoneCam
options:
  bundleIdPrefix: com.hobby
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "14.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.hobby.iphonecam
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.5"
    TARGETED_DEVICE_FAMILY: "1" # 1 = iPhone
    INFOPLIST_FILE: iPhoneCam/Info.plist
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""
    ENABLE_BITCODE: NO

targets:
  iPhoneCam:
    type: application
    platform: iOS
    sources:
      - path: iPhoneCam
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
